# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build 
      run: |
        npm ci
        npm run build --if-present
        
    - name: Release Github Pages
      uses: igolopolosov/github-action-release-github-pages@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: afuentes
        GITHUB_PAGES_REPO_NAME: afuentes.github.io
        GITHUB_PAGES_RELEASE_BRANCH: master
        PROJECT_BUILD_FOLDER: dist
        GITHUB_PAGES_CLEANUP_SCRIPT: "rm bundle* && rm index.html"

